name: Lobby
version: '${project.version}'
main: vip.marcel.gamestarbro.lobby.Lobby
api-version: 1.15
authors: [ VIPMarcel ]
description: the official lobby system for gamestarbro

depend:
  - ProtocolLib

softdepend:
  - PlaceholderAPI

commands:
  crash:
    description: crash a player
  edit:
    description: edit the lobby
  fly:
    description: enable or disable fly mode
  setposition:
    description: set teleport position
    aliases:
      - setpos
  setupjnr:
    description: setup the jump and run
  setuptopwall:
    description: setup the top 3 players wall
  updateplayerwall:
    description: force update the top 3 players wall
  togglegame:
    description: set gamemodies in maintenance mode or release them